### ISSUE TITLE
ExtendedSliverGrid的viewportBuilder会出现-1

### ISSUE THREAD

**Issue by choykarl** [fluttercandies/extended_list#4]
![image](https://user-images.githubusercontent.com/12951859/86771322-99657280-c084-11ea-862d-182bd7a1c720.png)

在滚动到item之间的空隙里的时候就会出现-1

**Comment by zmtzawqlp** [comment]
请提供简单demo

**Comment by choykarl** [comment]
[flutter_app.zip](https://github.com/fluttercandies/extended_list/files/4886058/flutter_app.zip)

[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.17.3 at /Users/caihaohao/Desktop/flutter/flutter
    • Framework revision b041144f83 (5 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4
滚动到空白处的时候就会出现-1。
是iOS设备。
@zmtzawqlp
