### ISSUE TITLE
点击事件监听无效

### ISSUE THREAD

**Issue by ToZhanChi** [fluttercandies/extended_list#6]
GestureDetector：
在列表的最后一个元素，在第一次接收点击事件后刷新，之后点击事件将再也收不到。

换成InkWell后就正常了！

**Comment by zmtzawqlp** [comment]
请提供可以运行并且重现问题的demo

**Comment by ToZhanChi** [comment]
[main.zip](https://github.com/fluttercandies/extended_list/files/5139524/main.zip)
你看看能不能复现，不能复现我就把环境也给你。

**Comment by ToZhanChi** [comment]
复现了吗？

**Comment by zmtzawqlp** [comment]
packages/flutter/lib/src/widgets/sliver.dart        

     if (index == 0) {
            parentData.layoutOffset = 0.0;
          } else if (indexToLayoutOffset.containsKey(index)) {
            parentData.layoutOffset = indexToLayoutOffset[index];
          }

setstate之后，官方悄悄把layoutOffset改了。有点恶心，不是读的缓存的，而且直接设置成0了。

**Comment by zmtzawqlp** [comment]
获取最新版本，已经解决 https://github.com/fluttercandies/extended_list/commit/fcacf0688c57d7a2134a3448e41a7f3dd901f231
